begin;

revoke all on function public.upsert_customer_by_identity(uuid, text, text, text, text, uuid) from public;
revoke all on function public.upsert_customer_by_identity(uuid, text, text, text, text, uuid) from anon;
revoke all on function public.upsert_customer_by_identity(uuid, text, text, text, text) from public;
revoke all on function public.upsert_customer_by_identity(uuid, text, text, text, text) from anon;
revoke all on function public.list_team_members_secure() from public;
revoke all on function public.list_team_members_secure() from anon;
revoke all on function public.list_team_members_secure_v2() from public;
revoke all on function public.list_team_members_secure_v2() from anon;
revoke all on function public.get_ticket_detail_secure(uuid) from public;
revoke all on function public.get_ticket_detail_secure(uuid) from anon;
revoke all on function public.get_report_breakdown_secure(timestamptz, timestamptz) from public;
revoke all on function public.get_report_breakdown_secure(timestamptz, timestamptz) from anon;
revoke all on function public.get_report_breakdown_secure(timestamptz, timestamptz, uuid) from public;
revoke all on function public.get_report_breakdown_secure(timestamptz, timestamptz, uuid) from anon;
revoke all on function public.generate_invite_code_secure(text, text) from public;
revoke all on function public.generate_invite_code_secure(text, text) from anon;
revoke all on function public.generate_invite_code_secure(uuid, text, text) from public;
revoke all on function public.generate_invite_code_secure(uuid, text, text) from anon;
revoke all on function public.convert_booking_request_to_appointment_secure(uuid, uuid, uuid, timestamptz, timestamptz) from public;
revoke all on function public.convert_booking_request_to_appointment_secure(uuid, uuid, uuid, timestamptz, timestamptz) from anon;
revoke all on function public.checkout_close_ticket_secure(text, text, jsonb, uuid, int, text) from public;
revoke all on function public.checkout_close_ticket_secure(text, text, jsonb, uuid, int, text) from anon;
revoke all on function public.list_customers_crm(text, text, int, boolean, text) from public;
revoke all on function public.list_customers_crm(text, text, int, boolean, text) from anon;
revoke all on function public.list_customers_crm(text, text, int, boolean, text, uuid) from public;
revoke all on function public.list_customers_crm(text, text, int, boolean, text, uuid) from anon;
revoke all on function public.get_customer_crm_detail(uuid) from public;
revoke all on function public.get_customer_crm_detail(uuid) from anon;
revoke all on function public.update_customer_care_note(uuid, text, text[], timestamptz, text) from public;
revoke all on function public.update_customer_care_note(uuid, text, text[], timestamptz, text) from anon;
revoke all on function public.list_follow_up_candidates(timestamptz, timestamptz) from public;
revoke all on function public.list_follow_up_candidates(timestamptz, timestamptz) from anon;
revoke all on function public.list_follow_up_candidates(timestamptz, timestamptz, uuid) from public;
revoke all on function public.list_follow_up_candidates(timestamptz, timestamptz, uuid) from anon;

grant execute on function public.upsert_customer_by_identity(uuid, text, text, text, text, uuid) to authenticated, service_role;
grant execute on function public.upsert_customer_by_identity(uuid, text, text, text, text) to authenticated, service_role;
grant execute on function public.list_team_members_secure() to authenticated;
grant execute on function public.list_team_members_secure_v2() to authenticated;
grant execute on function public.get_ticket_detail_secure(uuid) to authenticated;
grant execute on function public.get_report_breakdown_secure(timestamptz, timestamptz) to authenticated;
grant execute on function public.get_report_breakdown_secure(timestamptz, timestamptz, uuid) to authenticated;
grant execute on function public.generate_invite_code_secure(text, text) to authenticated;
grant execute on function public.generate_invite_code_secure(uuid, text, text) to authenticated;
grant execute on function public.convert_booking_request_to_appointment_secure(uuid, uuid, uuid, timestamptz, timestamptz) to authenticated;
grant execute on function public.checkout_close_ticket_secure(text, text, jsonb, uuid, int, text) to authenticated;
grant execute on function public.list_customers_crm(text, text, int, boolean, text) to authenticated;
grant execute on function public.list_customers_crm(text, text, int, boolean, text, uuid) to authenticated;
grant execute on function public.get_customer_crm_detail(uuid) to authenticated;
grant execute on function public.update_customer_care_note(uuid, text, text[], timestamptz, text) to authenticated;
grant execute on function public.list_follow_up_candidates(timestamptz, timestamptz) to authenticated;
grant execute on function public.list_follow_up_candidates(timestamptz, timestamptz, uuid) to authenticated;

commit;
